server:
  port: 8081
spring:
  application:
    name: "Applications"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    active: docker
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapters:
  postgres:
    database: ${DATABASE_APP}
    host: ${DB_HOST}
    port: 5432
    username: ${USERNAME_APP}
    password: ${PASSWORD_APP}
    schema: "public"
    pool:
      initial-size: 12
      max-size: 15
      max-idle-time: 10

  reactive-web:
    base-path: "api/v1/solicitudes"

jwt:
  secret: ${JWT_SECRET}
  service-token: ${ROL_SERVICE_TOKEN}

logging:
  level:
    io.r2dbc.postgresql: INFO
    io.r2dbc.spi.ConnectionFactory: INFO

adapter:
  sqs:
    region: ${AWS_REGION}
    queues:
      notifications: ${AWS_QUEUE_NOTIFICATIONS_URL}
      reports: ${AWS_QUEUE_REPORTS_URL}

  authentication:
    base-url: ${AUTH_ENDPOINT}

  lambda-validation:
    base-url: ${CAPACITY_LAMBDA_URL}
