# Database Configuration
adapters.postgres.host=${DB_HOST}
adapters.postgres.port=5432
adapters.postgres.database=${DATABASE_APP}
adapters.postgres.username=${USERNAME_APP}
adapters.postgres.password=${PASSWORD_APP}

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.service-token=${ROL_SERVICE_TOKEN}

# Server
server.port=8081

# Web Client
#adapter.authentication.base-url=http://authentication-service:8080/api/v1
adapter.authentication.base-url=${AUTH_ENDPOINT}
adapter.lambda-validation.base-url= ${CAPACITY_LAMBDA_URL}

# Configuración SQS
adapter.sqs.region= ${AWS_REGION}
adapter.sqs.queues.notifications= ${AWS_QUEUE_NOTIFICATIONS_URL}
adapter.sqs.queues.reports= ${AWS_QUEUE_REPORTS_URL}