# Database Configuration
adapters.postgres.host=${DB_HOST}
adapters.postgres.port=5432
adapters.postgres.database=${DATABASE_APP}
adapters.postgres.username=${USERNAME_APP}
adapters.postgres.password=${PASSWORD_APP}

# JWT Configuration
jwt.secret=${JWT_SECRET_APP}

# Server
server.port=8081

# Web Client (usa el nombre del servicio Docker)
adapters.driven-adapters.web-client.authentication.base-url=http://authentication-service:8080/api/v1

## Configuración de AWS
#aws.access-key-id=${AWS_ACCESS_KEY_ID}
#aws.secret-access-key=${AWS_SECRET_ACCESS_KEY}

# Configuración SQS
adapter.sqs.region= ${AWS_REGION}
adapter.sqs.queueUrl= ${AWS_SQS_QUEUE_URL}