# Database Configuration
adapters.postgres.host=${DB_HOST}
adapters.postgres.port=5432
adapters.postgres.database=${DATABASE_APP}
adapters.postgres.username=${USERNAME_APP}
adapters.postgres.password=${PASSWORD_APP}

# JWT Configuration
jwt.secret=${JWT_SECRET_APP}
jwt.service-token=${ROL_SERVICE_TOKEN}

# Server
server.port=8081

# Web Client
adapter.authentication.base-url=http://authentication-service:8080/api/v1
adapter.lambda-validation.base-url= ${CAPACITY_URL_LAMBDA}

# Configuración SQS
adapter.sqs.region= ${AWS_REGION}
adapter.sqs.queueUrl= ${AWS_SQS_QUEUE_URL}